import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>低代码平台</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="err">
          id 信息有误，请检查之后重新输入
        </div>
      </main>
    </>
  );
}
